export const GALERIJA: any = [
    {
        id: 1,
        description: "Didysis Vabalų Suvažiavimas 16",
        videoUrl1: '',
        iconUrl1: '../../assets/renginiai/Didysis Vabalų Suvažiavimas 16/_DSC0066.JPG',
        iconUrl2: '../../assets/renginiai/Didysis Vabalų Suvažiavimas 16/_DSC0088.JPG',
        iconUrl3: '../../assets/renginiai/Didysis Vabalų Suvažiavimas 16/_DSC0109.JPG',
        iconUrl4: '../../assets/renginiai/Didysis Vabalų Suvažiavimas 16/_DSC0146.JPG',
        iconUrl5: '../../assets/renginiai/Didysis Vabalų Suvažiavimas 16/_DSC0210.JPG',
        iconUrl6: '../../assets/renginiai/Didysis Vabalų Suvažiavimas 16/_DSC0237.JPG',
        iconUrl7: '../../assets/renginiai/Didysis Vabalų Suvažiavimas 16/_DSC0240.JPG',
        iconUrl8: '../../assets/renginiai/Didysis Vabalų Suvažiavimas 16/_DSC0241.JPG',
        iconUrl9: '../../assets/renginiai/Didysis Vabalų Suvažiavimas 16/_DSC0242.JPG',
        iconUrl10: '../../assets/renginiai/Didysis Vabalų Suvažiavimas 16/_DSC0243.JPG',
        iconUrl11: '../../assets/renginiai/Didysis Vabalų Suvažiavimas 16/_DSC0247.JPG',
        iconUrl12: '../../assets/renginiai/Didysis Vabalų Suvažiavimas 16/_DSC0250.JPG',
        iconUrl13: '../../assets/renginiai/Didysis Vabalų Suvažiavimas 16/_DSC0254.JPG',
        iconUrl14: '../../assets/renginiai/Didysis Vabalų Suvažiavimas 16/_DSC0255.JPG',
        iconUrl15: '../../assets/renginiai/Didysis Vabalų Suvažiavimas 16/_DSC0256.JPG',
        iconUrl16: '../../assets/renginiai/Didysis Vabalų Suvažiavimas 16/_DSC0259.JPG',
        iconUrl17: '../../assets/renginiai/Didysis Vabalų Suvažiavimas 16/_DSC0260.JPG',
        iconUrl18: '../../assets/renginiai/Didysis Vabalų Suvažiavimas 16/_DSC0262.JPG',
        iconUrl19: '../../assets/renginiai/Didysis Vabalų Suvažiavimas 16/_DSC0265.JPG',
        iconUrl20: '../../assets/renginiai/Didysis Vabalų Suvažiavimas 16/_DSC0271.JPG',
        iconUrl21: '../../assets/renginiai/Didysis Vabalų Suvažiavimas 16/_DSC0273.JPG',
        iconUrl22: '../../assets/renginiai/Didysis Vabalų Suvažiavimas 16/_DSC0276.JPG',
        iconUrl23: '../../assets/renginiai/Didysis Vabalų Suvažiavimas 16/_DSC0278.JPG',
        iconUrl24: '../../assets/renginiai/Didysis Vabalų Suvažiavimas 16/_DSC0281.JPG',
        iconUrl25: '../../assets/renginiai/Didysis Vabalų Suvažiavimas 16/_DSC0282.JPG',
        iconUrl26: '../../assets/renginiai/Didysis Vabalų Suvažiavimas 16/_DSC0286.JPG',
        iconUrl27: '../../assets/renginiai/Didysis Vabalų Suvažiavimas 16/_DSC0287.JPG',
        iconUrl28: '../../assets/renginiai/Didysis Vabalų Suvažiavimas 16/_DSC0291.JPG',
        iconUrl29: '../../assets/renginiai/Didysis Vabalų Suvažiavimas 16/_DSC0293.JPG',
        iconUrl30: '',
        iconUrl31: '',
        iconUrl32: '',
        iconUrl33: '',
        iconUrl34: '',
        iconUrl35: '',
        iconUrl36: '',
        iconUrl37: '',
        iconUrl38: '',
        iconUrl39: '',
        iconUrl40: '',
        iconUrl41: '',
        iconUrl1Alt: '',
        iconUrl2Alt: '',
        iconUrl3Alt: '',
        iconUrl4Alt: '',
        iconUrl5Alt: '',
        iconUrl6Alt: '',
        iconUrl7Alt: '',
        iconUrl8Alt: '',
        iconUrl9Alt: '',
        iconUrl10Alt: '',
        iconUrl11Alt: '',
        iconUrl12Alt: '',
        iconUrl13Alt: '',
        iconUrl14Alt: '',
        iconUrl15Alt: '',
        iconUrl16Alt: '',
        iconUrl17Alt: '',
        iconUrl18Alt: '',
        iconUrl19Alt: '',
        iconUrl20Alt: '',
        iconUrl21Alt: '',
        iconUrl22Alt: '',
        iconUrl23Alt: '',
        iconUrl24Alt: '',
        iconUrl25Alt: '',
        iconUrl26Alt: '',
        iconUrl27Alt: '',
        iconUrl28Alt: '',
        iconUrl29Alt: '',
        iconUrl30Alt: '',
        iconUrl31Alt: '',
        iconUrl32Alt: '',
        iconUrl33Alt: '',
        iconUrl34Alt: '',
        iconUrl35Alt: '',
        iconUrl36Alt: '',
        iconUrl37Alt: '',
        iconUrl38Alt: '',
        iconUrl39Alt: '',
        iconUrl40Alt: '',
        iconUrl41Alt: '',
        longDescription1: "",
        longDescription2: "",
        longDescription3: "",
        longDescription4: "",
        longDescription5: "",
        longDescription6: "",
        year: '2016',
        month: '01',
        day: '01',
        logoUrl1: "../../assets/LOGO/logo_vektorius.svg",
        logoUrl2: "",
        cardImg: ''
    },
    {
        id: 2,
        description: "Dzūkijos Vasara 16",
        videoUrl1: '',
        iconUrl1: '../../assets/renginiai/Dzūkijos Vasara 16/_DSC9497.JPG',
        iconUrl2: '../../assets/renginiai/Dzūkijos Vasara 16/_DSC9507.JPG',
        iconUrl3: '../../assets/renginiai/Dzūkijos Vasara 16/_DSC9523.JPG',
        iconUrl4: '../../assets/renginiai/Dzūkijos Vasara 16/_DSC9567.JPG',
        iconUrl5: '../../assets/renginiai/Dzūkijos Vasara 16/_DSC9618.JPG',
        iconUrl6: '../../assets/renginiai/Dzūkijos Vasara 16/_DSC9669.JPG',
        iconUrl7: '../../assets/renginiai/Dzūkijos Vasara 16/_DSC9709.JPG',
        iconUrl8: '../../assets/renginiai/Dzūkijos Vasara 16/_DSC9717.JPG',
        iconUrl9: '../../assets/renginiai/Dzūkijos Vasara 16/_DSC9811.JPG',
        iconUrl10: '../../assets/renginiai/Dzūkijos Vasara 16/_DSC9822.JPG',
        iconUrl11: '../../assets/renginiai/Dzūkijos Vasara 16/DSC_0847.JPG',
        iconUrl12: '../../assets/renginiai/Dzūkijos Vasara 16/DSC_0853.JPG',
        iconUrl13: '../../assets/renginiai/Dzūkijos Vasara 16/DSC_0891.JPG',
        iconUrl14: '../../assets/renginiai/Dzūkijos Vasara 16/DSC_0891 (1).JPG',
        iconUrl15: '../../assets/renginiai/Dzūkijos Vasara 16/DSC_0898.JPG',
        iconUrl16: '../../assets/renginiai/Dzūkijos Vasara 16/DSC_0909.JPG',
        iconUrl17: '../../assets/renginiai/Dzūkijos Vasara 16/DSC_0951.JPG',
        iconUrl18: '../../assets/renginiai/Dzūkijos Vasara 16/DSC_0960.JPG',
        iconUrl19: '../../assets/renginiai/Dzūkijos Vasara 16/DSC_3287.JPG',
        iconUrl20: '../../assets/renginiai/Dzūkijos Vasara 16/IMG_6313.jpg',
        iconUrl21: '../../assets/renginiai/Dzūkijos Vasara 16/IMG_6323.jpg',
        iconUrl22: '../../assets/renginiai/Dzūkijos Vasara 16/IMG_7186.jpg',
        iconUrl23: '../../assets/renginiai/Dzūkijos Vasara 16/IMG_7203.jpg',
        iconUrl24: '../../assets/renginiai/Dzūkijos Vasara 16/IMG_7229.jpg',
        iconUrl25: '../../assets/renginiai/Dzūkijos Vasara 16/IMG_7239.jpg',
        iconUrl26: '../../assets/renginiai/Dzūkijos Vasara 16/IMG_7263.jpg',
        iconUrl27: '../../assets/renginiai/Dzūkijos Vasara 16/IMG_7273.jpg',
        iconUrl28: '../../assets/renginiai/Dzūkijos Vasara 16/IMG_7301.jpg',
        iconUrl29: '../../assets/renginiai/Dzūkijos Vasara 16/IMG_7361.jpg',
        iconUrl30: '../../assets/renginiai/Dzūkijos Vasara 16/IMG_7365.jpg',
        iconUrl31: '../../assets/renginiai/Dzūkijos Vasara 16/IMG_7370.jpg',
        iconUrl32: '../../assets/renginiai/Dzūkijos Vasara 16/IMG_7376.jpg',
        iconUrl33: '../../assets/renginiai/Dzūkijos Vasara 16/IMG_7726.jpg',
        iconUrl34: '../../assets/renginiai/Dzūkijos Vasara 16/IMG_7989.jpg',
        iconUrl35: '../../assets/renginiai/Dzūkijos Vasara 16/IMG_8024.jpg',
        iconUrl36: '../../assets/renginiai/Dzūkijos Vasara 16/IMG_8040.jpg',
        iconUrl37: '../../assets/renginiai/Dzūkijos Vasara 16/IMG_8055.jpg',
        iconUrl38: '../../assets/renginiai/Dzūkijos Vasara 16/IMG_8076.jpg',
        iconUrl39: '../../assets/renginiai/Dzūkijos Vasara 16/IMG_8089.jpg',
        iconUrl40: '../../assets/renginiai/Dzūkijos Vasara 16/_DSC9695.JPG',
        iconUrl41: '',
        iconUrl1Alt: '',
        iconUrl2Alt: '',
        iconUrl3Alt: '',
        iconUrl4Alt: '',
        iconUrl5Alt: '',
        iconUrl6Alt: '',
        iconUrl7Alt: '',
        iconUrl8Alt: '',
        iconUrl9Alt: '',
        iconUrl10Alt: '',
        iconUrl11Alt: '',
        iconUrl12Alt: '',
        iconUrl13Alt: '',
        iconUrl14Alt: '',
        iconUrl15Alt: '',
        iconUrl16Alt: '',
        iconUrl17Alt: '',
        iconUrl18Alt: '',
        iconUrl19Alt: '',
        iconUrl20Alt: '',
        iconUrl21Alt: '',
        iconUrl22Alt: '',
        iconUrl23Alt: '',
        iconUrl24Alt: '',
        iconUrl25Alt: '',
        iconUrl26Alt: '',
        iconUrl27Alt: '',
        iconUrl28Alt: '',
        iconUrl29Alt: '',
        iconUrl30Alt: '',
        iconUrl31Alt: '',
        iconUrl32Alt: '',
        iconUrl33Alt: '',
        iconUrl34Alt: '',
        iconUrl35Alt: '',
        iconUrl36Alt: '',
        iconUrl37Alt: '',
        iconUrl38Alt: '',
        iconUrl39Alt: '',
        iconUrl40Alt: '',
        iconUrl41Alt: '',
        longDescription1: "",
        longDescription2: "",
        longDescription3: "",
        longDescription4: "",
        longDescription5: "",
        longDescription6: "",
        year: '2016',
        month: '01',
        day: '01',
        logoUrl1: "../../assets/LOGO/logo_vektorius.svg",
        logoUrl2: "",
        cardImg: ''
    },
    {
        id: 3,
        description: "Gyvūnų diena Vilniuje 2015",
        videoUrl1: '',
        iconUrl1: '../../assets/renginiai/Gyvunu diena Vilniuje 2015/DSC_0461.JPG',
        iconUrl2: '../../assets/renginiai/Gyvunu diena Vilniuje 2015/DSC_0463.JPG',
        iconUrl3: '../../assets/renginiai/Gyvunu diena Vilniuje 2015/DSC_0483.JPG',
        iconUrl4: '../../assets/renginiai/Gyvunu diena Vilniuje 2015/DSC_0491.JPG',
        iconUrl5: '../../assets/renginiai/Gyvunu diena Vilniuje 2015/DSC_0506.JPG',
        iconUrl6: '../../assets/renginiai/Gyvunu diena Vilniuje 2015/DSC_0532.JPG',
        iconUrl7: '../../assets/renginiai/Gyvunu diena Vilniuje 2015/DSC_0548.JPG',
        iconUrl8: '../../assets/renginiai/Gyvunu diena Vilniuje 2015/DSC_0550.JPG',
        iconUrl9: '../../assets/renginiai/Gyvunu diena Vilniuje 2015/DSC_0566.JPG',
        iconUrl10: '../../assets/renginiai/Gyvunu diena Vilniuje 2015/DSC_0585.JPG',
        iconUrl11: '../../assets/renginiai/Gyvunu diena Vilniuje 2015/DSC_0587.JPG',
        iconUrl12: '../../assets/renginiai/Gyvunu diena Vilniuje 2015/DSC_0606.JPG',
        iconUrl13: '../../assets/renginiai/Gyvunu diena Vilniuje 2015/DSC_0635.JPG',
        iconUrl14: '../../assets/renginiai/Gyvunu diena Vilniuje 2015/DSC_0647.JPG',
        iconUrl15: '../../assets/renginiai/Gyvunu diena Vilniuje 2015/DSC_0704.JPG',
        iconUrl16: '../../assets/renginiai/Gyvunu diena Vilniuje 2015/DSC_0717.JPG',
        iconUrl17: '../../assets/renginiai/Gyvunu diena Vilniuje 2015/DSC_0725.JPG',
        iconUrl18: '../../assets/renginiai/Gyvunu diena Vilniuje 2015/DSC_0726.JPG',
        iconUrl19: '../../assets/renginiai/Gyvunu diena Vilniuje 2015/DSC_0747.JPG',
        iconUrl20: '../../assets/renginiai/Gyvunu diena Vilniuje 2015/DSC_0767.JPG',
        iconUrl21: '../../assets/renginiai/Gyvunu diena Vilniuje 2015/DSC_0770.JPG',
        iconUrl22: '../../assets/renginiai/Gyvunu diena Vilniuje 2015/DSC_0774.JPG',
        iconUrl23: '../../assets/renginiai/Gyvunu diena Vilniuje 2015/DSC_0780.JPG',
        iconUrl24: '../../assets/renginiai/Gyvunu diena Vilniuje 2015/DSC_0786.JPG',
        iconUrl25: '',
        iconUrl26: '',
        iconUrl27: '',
        iconUrl28: '',
        iconUrl29: '',
        iconUrl30: '',
        iconUrl31: '',
        iconUrl32: '',
        iconUrl33: '',
        iconUrl34: '',
        iconUrl35: '',
        iconUrl36: '',
        iconUrl37: '',
        iconUrl38: '',
        iconUrl39: '',
        iconUrl40: '',
        iconUrl41: '',
        iconUrl1Alt: '',
        iconUrl2Alt: '',
        iconUrl3Alt: '',
        iconUrl4Alt: '',
        iconUrl5Alt: '',
        iconUrl6Alt: '',
        iconUrl7Alt: '',
        iconUrl8Alt: '',
        iconUrl9Alt: '',
        iconUrl10Alt: '',
        iconUrl11Alt: '',
        iconUrl12Alt: '',
        iconUrl13Alt: '',
        iconUrl14Alt: '',
        iconUrl15Alt: '',
        iconUrl16Alt: '',
        iconUrl17Alt: '',
        iconUrl18Alt: '',
        iconUrl19Alt: '',
        iconUrl20Alt: '',
        iconUrl21Alt: '',
        iconUrl22Alt: '',
        iconUrl23Alt: '',
        iconUrl24Alt: '',
        iconUrl25Alt: '',
        iconUrl26Alt: '',
        iconUrl27Alt: '',
        iconUrl28Alt: '',
        iconUrl29Alt: '',
        iconUrl30Alt: '',
        iconUrl31Alt: '',
        iconUrl32Alt: '',
        iconUrl33Alt: '',
        iconUrl34Alt: '',
        iconUrl35Alt: '',
        iconUrl36Alt: '',
        iconUrl37Alt: '',
        iconUrl38Alt: '',
        iconUrl39Alt: '',
        iconUrl40Alt: '',
        iconUrl41Alt: '',
        longDescription1: "",
        longDescription2: "",
        longDescription3: "",
        longDescription4: "",
        longDescription5: "",
        longDescription6: "",
        year: '2015',
        month: '01',
        day: '01',
        logoUrl1: "../../assets/LOGO/logo_vektorius.svg",
        logoUrl2: "",
        cardImg: ''
    },
    {
        id: 4,
        description: "Gyvūnų diena Vilniuje 18",
        videoUrl1: '',
        iconUrl1: '../../assets/renginiai/Gyvunu diena Vilniuje 18/43337702_2169006830027094_8302740999478706176_o.jpg',
        iconUrl2: '../../assets/renginiai/Gyvunu diena Vilniuje 18/DSC_0981.jpg',
        iconUrl3: '../../assets/renginiai/Gyvunu diena Vilniuje 18/DSC_0988.jpg',
        iconUrl4: '../../assets/renginiai/Gyvunu diena Vilniuje 18/DSC_0993.jpg',
        iconUrl5: '../../assets/renginiai/Gyvunu diena Vilniuje 18/DSC_0995.jpg',
        iconUrl6: '../../assets/renginiai/Gyvunu diena Vilniuje 18/DSC_1003.jpg',
        iconUrl7: '../../assets/renginiai/Gyvunu diena Vilniuje 18/DSC_1013.jpg',
        iconUrl8: '../../assets/renginiai/Gyvunu diena Vilniuje 18/DSC_1057.jpg',
        iconUrl9: '../../assets/renginiai/Gyvunu diena Vilniuje 18/DSC_1072.jpg',
        iconUrl10: '../../assets/renginiai/Gyvunu diena Vilniuje 18/DSC_1077.jpg',
        iconUrl11: '../../assets/renginiai/Gyvunu diena Vilniuje 18/DSC_1078.jpg',
        iconUrl12: '../../assets/renginiai/Gyvunu diena Vilniuje 18/DSC_1086.jpg',
        iconUrl13: '../../assets/renginiai/Gyvunu diena Vilniuje 18/DSC_1093.jpg',
        iconUrl14: '',
        iconUrl15: '',
        iconUrl16: '',
        iconUrl17: '',
        iconUrl18: '',
        iconUrl19: '',
        iconUrl20: '',
        iconUrl21: '',
        iconUrl22: '',
        iconUrl23: '',
        iconUrl24: '',
        iconUrl25: '',
        iconUrl26: '',
        iconUrl27: '',
        iconUrl28: '',
        iconUrl29: '',
        iconUrl30: '',
        iconUrl31: '',
        iconUrl32: '',
        iconUrl33: '',
        iconUrl34: '',
        iconUrl35: '',
        iconUrl36: '',
        iconUrl37: '',
        iconUrl38: '',
        iconUrl39: '',
        iconUrl40: '',
        iconUrl41: '',
        iconUrl1Alt: '',
        iconUrl2Alt: '',
        iconUrl3Alt: '',
        iconUrl4Alt: '',
        iconUrl5Alt: '',
        iconUrl6Alt: '',
        iconUrl7Alt: '',
        iconUrl8Alt: '',
        iconUrl9Alt: '',
        iconUrl10Alt: '',
        iconUrl11Alt: '',
        iconUrl12Alt: '',
        iconUrl13Alt: '',
        iconUrl14Alt: '',
        iconUrl15Alt: '',
        iconUrl16Alt: '',
        iconUrl17Alt: '',
        iconUrl18Alt: '',
        iconUrl19Alt: '',
        iconUrl20Alt: '',
        iconUrl21Alt: '',
        iconUrl22Alt: '',
        iconUrl23Alt: '',
        iconUrl24Alt: '',
        iconUrl25Alt: '',
        iconUrl26Alt: '',
        iconUrl27Alt: '',
        iconUrl28Alt: '',
        iconUrl29Alt: '',
        iconUrl30Alt: '',
        iconUrl31Alt: '',
        iconUrl32Alt: '',
        iconUrl33Alt: '',
        iconUrl34Alt: '',
        iconUrl35Alt: '',
        iconUrl36Alt: '',
        iconUrl37Alt: '',
        iconUrl38Alt: '',
        iconUrl39Alt: '',
        iconUrl40Alt: '',
        iconUrl41Alt: '',
        longDescription1: "",
        longDescription2: "",
        longDescription3: "",
        longDescription4: "",
        longDescription5: "",
        longDescription6: "",
        year: '2018',
        month: '01',
        day: '01',
        logoUrl1: "../../assets/LOGO/logo_vektorius.svg",
        logoUrl2: "",
        cardImg: ''
    },
    
  
    {
        id: 7,
        description: "Kaziuko mugė 16",
        videoUrl1: '',
        iconUrl1: '../../assets/renginiai/Kaziuko mugė 16/IMG_6258.jpg',
        iconUrl2: '../../assets/renginiai/Kaziuko mugė 16/IMG_6274.jpg',
        iconUrl3: '../../assets/renginiai/Kaziuko mugė 16/IMG_6285.jpg',
        iconUrl4: '../../assets/renginiai/Kaziuko mugė 16/IMG_6315.jpg',
        iconUrl5: '../../assets/renginiai/Kaziuko mugė 16/IMG_6333.jpg',
        iconUrl6: '../../assets/renginiai/Kaziuko mugė 16/IMG_6336.jpg',
        iconUrl7: '../../assets/renginiai/Kaziuko mugė 16/IMG_6338.jpg',
        iconUrl8: '../../assets/renginiai/Kaziuko mugė 16/IMG_6353.jpg',
        iconUrl9: '../../assets/renginiai/Kaziuko mugė 16/IMG_6355.jpg',
        iconUrl10: '../../assets/renginiai/Kaziuko mugė 16/IMG_6371.jpg',
        iconUrl11: '../../assets/renginiai/Kaziuko mugė 16/IMG_6391.jpg',
        iconUrl12: '../../assets/renginiai/Kaziuko mugė 16/IMG_6424.jpg',
        iconUrl13: '../../assets/renginiai/Kaziuko mugė 16/IMG_6433.jpg',
        iconUrl14: '../../assets/renginiai/Kaziuko mugė 16/IMG_6464.jpg',
        iconUrl15: '../../assets/renginiai/Kaziuko mugė 16/IMG_6469.jpg',
        iconUrl16: '../../assets/renginiai/Kaziuko mugė 16/IMG_6479.jpg',
        iconUrl17: '../../assets/renginiai/Kaziuko mugė 16/IMG_6506.jpg',
        iconUrl18: '../../assets/renginiai/Kaziuko mugė 16/IMG_6518.jpg',
        iconUrl19: '../../assets/renginiai/Kaziuko mugė 16/IMG_6535.jpg',
        iconUrl20: '../../assets/renginiai/Kaziuko mugė 16/IMG_6537.jpg',
        iconUrl21: '../../assets/renginiai/Kaziuko mugė 16/IMG_6539.jpg',
        iconUrl22: '../../assets/renginiai/Kaziuko mugė 16/IMG_6548.jpg',
        iconUrl23: '../../assets/renginiai/Kaziuko mugė 16/IMG_6570.jpg',
        iconUrl24: '../../assets/renginiai/Kaziuko mugė 16/IMG_6586.jpg',
        iconUrl25: '../../assets/renginiai/Kaziuko mugė 16/IMG_6593.jpg',
        iconUrl26: '../../assets/renginiai/Kaziuko mugė 16/IMG_6600.jpg',
        iconUrl27: '../../assets/renginiai/Kaziuko mugė 16/IMG_6609.jpg',
        iconUrl28: '../../assets/renginiai/Kaziuko mugė 16/IMG_6641.jpg',
        iconUrl29: '../../assets/renginiai/Kaziuko mugė 16/IMG_6689.jpg',
        iconUrl30: '',
        iconUrl31: '',
        iconUrl32: '',
        iconUrl33: '',
        iconUrl34: '',
        iconUrl35: '',
        iconUrl36: '',
        iconUrl37: '',
        iconUrl38: '',
        iconUrl39: '',
        iconUrl40: '',
        iconUrl41: '',
        iconUrl1Alt: '',
        iconUrl2Alt: '',
        iconUrl3Alt: '',
        iconUrl4Alt: '',
        iconUrl5Alt: '',
        iconUrl6Alt: '',
        iconUrl7Alt: '',
        iconUrl8Alt: '',
        iconUrl9Alt: '',
        iconUrl10Alt: '',
        iconUrl11Alt: '',
        iconUrl12Alt: '',
        iconUrl13Alt: '',
        iconUrl14Alt: '',
        iconUrl15Alt: '',
        iconUrl16Alt: '',
        iconUrl17Alt: '',
        iconUrl18Alt: '',
        iconUrl19Alt: '',
        iconUrl20Alt: '',
        iconUrl21Alt: '',
        iconUrl22Alt: '',
        iconUrl23Alt: '',
        iconUrl24Alt: '',
        iconUrl25Alt: '',
        iconUrl26Alt: '',
        iconUrl27Alt: '',
        iconUrl28Alt: '',
        iconUrl29Alt: '',
        iconUrl30Alt: '',
        iconUrl31Alt: '',
        iconUrl32Alt: '',
        iconUrl33Alt: '',
        iconUrl34Alt: '',
        iconUrl35Alt: '',
        iconUrl36Alt: '',
        iconUrl37Alt: '',
        iconUrl38Alt: '',
        iconUrl39Alt: '',
        iconUrl40Alt: '',
        iconUrl41Alt: '',
        longDescription1: "",
        longDescription2: "",
        longDescription3: "",
        longDescription4: "",
        longDescription5: "",
        longDescription6: "",
        year: '2016',
        month: '01',
        day: '01',
        logoUrl1: "../../assets/LOGO/logo_vektorius.svg",
        logoUrl2: "",
        cardImg: ''
    },
    {
        id: 8,
        description: "Lietuvos šunų čempionų čempionatas 19",
        videoUrl1: '',
        iconUrl1: '../../assets/renginiai/Lietuvos šunų čempionų čempionatas 19/49298248_10214568521181760_6985332606896177152_o.jpg',
        iconUrl2: '../../assets/renginiai/Lietuvos šunų čempionų čempionatas 19/49335099_10214564119551722_2357794328035721216_o.jpg',
        iconUrl3: '../../assets/renginiai/Lietuvos šunų čempionų čempionatas 19/49403664_10214568534782100_6686000023752146944_o.jpg',
        iconUrl4: '../../assets/renginiai/Lietuvos šunų čempionų čempionatas 19/49764934_10214564070150487_8800195235666722816_o.jpg',
        iconUrl5: '../../assets/renginiai/Lietuvos šunų čempionų čempionatas 19/49899857_10214564106711401_778019809408319488_o.jpg',
        iconUrl6: '../../assets/renginiai/Lietuvos šunų čempionų čempionatas 19/49899965_10214568535262112_4709795114556325888_o.jpg',
        iconUrl7: '../../assets/renginiai/Lietuvos šunų čempionų čempionatas 19/49948871_10214568522541794_8563340549640159232_o.jpg',
        iconUrl8: '../../assets/renginiai/Lietuvos šunų čempionų čempionatas 19/49949577_10214564044549847_8024938090957111296_n.jpg',
        iconUrl9: '../../assets/renginiai/Lietuvos šunų čempionų čempionatas 19/49949915_10214564091711026_6395591746994044928_o.jpg',
        iconUrl10: '../../assets/renginiai/Lietuvos šunų čempionų čempionatas 19/50009505_10214564037029659_7872006829671186432_o.jpg',
        iconUrl11: '../../assets/renginiai/Lietuvos šunų čempionų čempionatas 19/50223037_10214564142112286_4514758038304849920_o.jpg',
        iconUrl12: '../../assets/renginiai/Lietuvos šunų čempionų čempionatas 19/50026320_10214564123831829_8615200965479366656_o.jpg',
        iconUrl13: '../../assets/renginiai/Lietuvos šunų čempionų čempionatas 19/50049731_10214568526061882_6489842648231182336_o.jpg',
        iconUrl14: '../../assets/renginiai/Lietuvos šunų čempionų čempionatas 19/50095587_10214564110071485_4611932214542729216_o.jpg',
        iconUrl15: '',
        iconUrl16: '',
        iconUrl17: '',
        iconUrl18: '',
        iconUrl19: '',
        iconUrl20: '',
        iconUrl21: '',
        iconUrl22: '',
        iconUrl23: '',
        iconUrl24: '',
        iconUrl25: '',
        iconUrl26: '',
        iconUrl27: '',
        iconUrl28: '',
        iconUrl29: '',
        iconUrl30: '',
        iconUrl31: '',
        iconUrl32: '',
        iconUrl33: '',
        iconUrl34: '',
        iconUrl35: '',
        iconUrl36: '',
        iconUrl37: '',
        iconUrl38: '',
        iconUrl39: '',
        iconUrl40: '',
        iconUrl41: '',
        iconUrl1Alt: '',
        iconUrl2Alt: '',
        iconUrl3Alt: '',
        iconUrl4Alt: '',
        iconUrl5Alt: '',
        iconUrl6Alt: '',
        iconUrl7Alt: '',
        iconUrl8Alt: '',
        iconUrl9Alt: '',
        iconUrl10Alt: '',
        iconUrl11Alt: '',
        iconUrl12Alt: '',
        iconUrl13Alt: '',
        iconUrl14Alt: '',
        iconUrl15Alt: '',
        iconUrl16Alt: '',
        iconUrl17Alt: '',
        iconUrl18Alt: '',
        iconUrl19Alt: '',
        iconUrl20Alt: '',
        iconUrl21Alt: '',
        iconUrl22Alt: '',
        iconUrl23Alt: '',
        iconUrl24Alt: '',
        iconUrl25Alt: '',
        iconUrl26Alt: '',
        iconUrl27Alt: '',
        iconUrl28Alt: '',
        iconUrl29Alt: '',
        iconUrl30Alt: '',
        iconUrl31Alt: '',
        iconUrl32Alt: '',
        iconUrl33Alt: '',
        iconUrl34Alt: '',
        iconUrl35Alt: '',
        iconUrl36Alt: '',
        iconUrl37Alt: '',
        iconUrl38Alt: '',
        iconUrl39Alt: '',
        iconUrl40Alt: '',
        iconUrl41Alt: '',
        longDescription1: "",
        longDescription2: "",
        longDescription3: "",
        longDescription4: "",
        longDescription5: "",
        longDescription6: "",
        year: '2019',
        month: '01',
        day: '01',
        logoUrl1: "../../assets/LOGO/logo_vektorius.svg",
        logoUrl2: "",
        cardImg: ''
    },
    {
        id: 9,
        description: "Pasirodymas Naisiuose 16",
        videoUrl1: '',
        iconUrl1: '../../assets/renginiai/Pasirodymas Naisiuose 16/IMG_2452.jpg',
        iconUrl2: '../../assets/renginiai/Pasirodymas Naisiuose 16/IMG_2472.jpg',
        iconUrl3: '../../assets/renginiai/Pasirodymas Naisiuose 16/IMG_2517.jpg',
        iconUrl4: '../../assets/renginiai/Pasirodymas Naisiuose 16/IMG_2692.jpg',
        iconUrl5: '../../assets/renginiai/Pasirodymas Naisiuose 16/IMG_2710.jpg',
        iconUrl6: '../../assets/renginiai/Pasirodymas Naisiuose 16/IMG_3034.jpg',
        iconUrl7: '../../assets/renginiai/Pasirodymas Naisiuose 16/IMG_3176.jpg',
        iconUrl8: '../../assets/renginiai/Pasirodymas Naisiuose 16/IMG_3319.jpg',
        iconUrl9: '../../assets/renginiai/Pasirodymas Naisiuose 16/IMG_3454.jpg',
        iconUrl10: '',
        iconUrl11: '',
        iconUrl12: '',
        iconUrl13: '',
        iconUrl14: '',
        iconUrl15: '',
        iconUrl16: '',
        iconUrl17: '',
        iconUrl18: '',
        iconUrl19: '',
        iconUrl20: '',
        iconUrl21: '',
        iconUrl22: '',
        iconUrl23: '',
        iconUrl24: '',
        iconUrl25: '',
        iconUrl26: '',
        iconUrl27: '',
        iconUrl28: '',
        iconUrl29: '',
        iconUrl30: '',
        iconUrl31: '',
        iconUrl32: '',
        iconUrl33: '',
        iconUrl34: '',
        iconUrl35: '',
        iconUrl36: '',
        iconUrl37: '',
        iconUrl38: '',
        iconUrl39: '',
        iconUrl40: '',
        iconUrl41: '',
        iconUrl1Alt: '',
        iconUrl2Alt: '',
        iconUrl3Alt: '',
        iconUrl4Alt: '',
        iconUrl5Alt: '',
        iconUrl6Alt: '',
        iconUrl7Alt: '',
        iconUrl8Alt: '',
        iconUrl9Alt: '',
        iconUrl10Alt: '',
        iconUrl11Alt: '',
        iconUrl12Alt: '',
        iconUrl13Alt: '',
        iconUrl14Alt: '',
        iconUrl15Alt: '',
        iconUrl16Alt: '',
        iconUrl17Alt: '',
        iconUrl18Alt: '',
        iconUrl19Alt: '',
        iconUrl20Alt: '',
        iconUrl21Alt: '',
        iconUrl22Alt: '',
        iconUrl23Alt: '',
        iconUrl24Alt: '',
        iconUrl25Alt: '',
        iconUrl26Alt: '',
        iconUrl27Alt: '',
        iconUrl28Alt: '',
        iconUrl29Alt: '',
        iconUrl30Alt: '',
        iconUrl31Alt: '',
        iconUrl32Alt: '',
        iconUrl33Alt: '',
        iconUrl34Alt: '',
        iconUrl35Alt: '',
        iconUrl36Alt: '',
        iconUrl37Alt: '',
        iconUrl38Alt: '',
        iconUrl39Alt: '',
        iconUrl40Alt: '',
        iconUrl41Alt: '',
        longDescription1: "",
        longDescription2: "",
        longDescription3: "",
        longDescription4: "",
        longDescription5: "",
        longDescription6: "",
        year: '2016',
        month: '01',
        day: '01',
        logoUrl1: "../../assets/LOGO/logo_vektorius.svg",
        logoUrl2: "",
        cardImg: ''
    },
    {
        id: 10,
        description: "ŠEIMOS SPORTO ŠVENTĖ SU KETURKOJAIS VILNIUJE 15",
        videoUrl1: '',
        iconUrl1: '../../assets/renginiai/ŠEIMOS SPORTO ŠVENTĖ SU KETURKOJAIS VILNIUJE 15/IMG_4627.JPG',
        iconUrl2: '../../assets/renginiai/ŠEIMOS SPORTO ŠVENTĖ SU KETURKOJAIS VILNIUJE 15/IMG_4631.JPG',
        iconUrl3: '../../assets/renginiai/ŠEIMOS SPORTO ŠVENTĖ SU KETURKOJAIS VILNIUJE 15/IMG_4633.JPG',
        iconUrl4: '../../assets/renginiai/ŠEIMOS SPORTO ŠVENTĖ SU KETURKOJAIS VILNIUJE 15/IMG_4642.JPG',
        iconUrl5: '../../assets/renginiai/ŠEIMOS SPORTO ŠVENTĖ SU KETURKOJAIS VILNIUJE 15/IMG_4654.JPG',
        iconUrl6: '../../assets/renginiai/ŠEIMOS SPORTO ŠVENTĖ SU KETURKOJAIS VILNIUJE 15/IMG_4677.JPG',
        iconUrl7: '../../assets/renginiai/ŠEIMOS SPORTO ŠVENTĖ SU KETURKOJAIS VILNIUJE 15/IMG_4692.JPG',
        iconUrl8: '../../assets/renginiai/ŠEIMOS SPORTO ŠVENTĖ SU KETURKOJAIS VILNIUJE 15/IMG_4727.JPG',
        iconUrl9: '../../assets/renginiai/ŠEIMOS SPORTO ŠVENTĖ SU KETURKOJAIS VILNIUJE 15/IMG_4732.JPG',
        iconUrl10: '../../assets/renginiai/ŠEIMOS SPORTO ŠVENTĖ SU KETURKOJAIS VILNIUJE 15/IMG_4749.JPG',
        iconUrl11: '../../assets/renginiai/ŠEIMOS SPORTO ŠVENTĖ SU KETURKOJAIS VILNIUJE 15/IMG_4754.JPG',
        iconUrl12: '../../assets/renginiai/ŠEIMOS SPORTO ŠVENTĖ SU KETURKOJAIS VILNIUJE 15/IMG_4752.JPG',
        iconUrl13: '',
        iconUrl14: '',
        iconUrl15: '',
        iconUrl16: '',
        iconUrl17: '',
        iconUrl18: '',
        iconUrl19: '',
        iconUrl20: '',
        iconUrl21: '',
        iconUrl22: '',
        iconUrl23: '',
        iconUrl24: '',
        iconUrl25: '',
        iconUrl26: '',
        iconUrl27: '',
        iconUrl28: '',
        iconUrl29: '',
        iconUrl30: '',
        iconUrl31: '',
        iconUrl32: '',
        iconUrl33: '',
        iconUrl34: '',
        iconUrl35: '',
        iconUrl36: '',
        iconUrl37: '',
        iconUrl38: '',
        iconUrl39: '',
        iconUrl40: '',
        iconUrl41: '',
        iconUrl1Alt: '',
        iconUrl2Alt: '',
        iconUrl3Alt: '',
        iconUrl4Alt: '',
        iconUrl5Alt: '',
        iconUrl6Alt: '',
        iconUrl7Alt: '',
        iconUrl8Alt: '',
        iconUrl9Alt: '',
        iconUrl10Alt: '',
        iconUrl11Alt: '',
        iconUrl12Alt: '',
        iconUrl13Alt: '',
        iconUrl14Alt: '',
        iconUrl15Alt: '',
        iconUrl16Alt: '',
        iconUrl17Alt: '',
        iconUrl18Alt: '',
        iconUrl19Alt: '',
        iconUrl20Alt: '',
        iconUrl21Alt: '',
        iconUrl22Alt: '',
        iconUrl23Alt: '',
        iconUrl24Alt: '',
        iconUrl25Alt: '',
        iconUrl26Alt: '',
        iconUrl27Alt: '',
        iconUrl28Alt: '',
        iconUrl29Alt: '',
        iconUrl30Alt: '',
        iconUrl31Alt: '',
        iconUrl32Alt: '',
        iconUrl33Alt: '',
        iconUrl34Alt: '',
        iconUrl35Alt: '',
        iconUrl36Alt: '',
        iconUrl37Alt: '',
        iconUrl38Alt: '',
        iconUrl39Alt: '',
        iconUrl40Alt: '',
        iconUrl41Alt: '',
        longDescription1: "",
        longDescription2: "",
        longDescription3: "",
        longDescription4: "",
        longDescription5: "",
        longDescription6: "",
        year: '2015',
        month: '01',
        day: '01',
        logoUrl1: "../../assets/LOGO/logo_vektorius.svg",
        logoUrl2: "",
        cardImg: ''
    },
    {
        id: 11,
        description: "Tarptautinė Šunų Paroda Druskininkuose 18",
        videoUrl1: '',
        iconUrl1: '../../assets/renginiai/Tarptautinė Šunų Paroda Druskininkuose 18/DSC_6439.jpg',
        iconUrl2: '../../assets/renginiai/Tarptautinė Šunų Paroda Druskininkuose 18/DSC_6440.jpg',
        iconUrl3: '../../assets/renginiai/Tarptautinė Šunų Paroda Druskininkuose 18/DSC_6442.jpg',
        iconUrl4: '../../assets/renginiai/Tarptautinė Šunų Paroda Druskininkuose 18/DSC_6448.jpg',
        iconUrl5: '../../assets/renginiai/Tarptautinė Šunų Paroda Druskininkuose 18/DSC_6449.jpg',
        iconUrl6: '../../assets/renginiai/Tarptautinė Šunų Paroda Druskininkuose 18/DSC_6453.jpg',
        iconUrl7: '../../assets/renginiai/Tarptautinė Šunų Paroda Druskininkuose 18/DSC_6459.jpg',
        iconUrl8: '../../assets/renginiai/Tarptautinė Šunų Paroda Druskininkuose 18/DSC_6470.jpg',
        iconUrl9: '../../assets/renginiai/Tarptautinė Šunų Paroda Druskininkuose 18/DSC_6474.jpg',
        iconUrl10: '../../assets/renginiai/Tarptautinė Šunų Paroda Druskininkuose 18/DSC_6478.jpg',
        iconUrl11: '../../assets/renginiai/Tarptautinė Šunų Paroda Druskininkuose 18/DSC_6593.jpg',
        iconUrl12: '../../assets/renginiai/Tarptautinė Šunų Paroda Druskininkuose 18/DSC_6481.jpg',
        iconUrl13: '../../assets/renginiai/Tarptautinė Šunų Paroda Druskininkuose 18/DSC_6484.jpg',
        iconUrl14: '../../assets/renginiai/Tarptautinė Šunų Paroda Druskininkuose 18/DSC_6486.jpg',
        iconUrl15: '../../assets/renginiai/Tarptautinė Šunų Paroda Druskininkuose 18/DSC_6490.jpg',
        iconUrl16: '../../assets/renginiai/Tarptautinė Šunų Paroda Druskininkuose 18/DSC_6500.jpg',
        iconUrl17: '../../assets/renginiai/Tarptautinė Šunų Paroda Druskininkuose 18/DSC_6512.jpg',
        iconUrl18: '../../assets/renginiai/Tarptautinė Šunų Paroda Druskininkuose 18/DSC_6520.jpg',
        iconUrl19: '../../assets/renginiai/Tarptautinė Šunų Paroda Druskininkuose 18/DSC_6524.jpg',
        iconUrl20: '../../assets/renginiai/Tarptautinė Šunų Paroda Druskininkuose 18/DSC_6529.jpg',
        iconUrl21: '../../assets/renginiai/Tarptautinė Šunų Paroda Druskininkuose 18/DSC_6534.jpg',
        iconUrl22: '../../assets/renginiai/Tarptautinė Šunų Paroda Druskininkuose 18/DSC_6543.jpg',
        iconUrl23: '../../assets/renginiai/Tarptautinė Šunų Paroda Druskininkuose 18/DSC_6546.jpg',
        iconUrl24: '../../assets/renginiai/Tarptautinė Šunų Paroda Druskininkuose 18/DSC_6547.jpg',
        iconUrl25: '../../assets/renginiai/Tarptautinė Šunų Paroda Druskininkuose 18/DSC_6554.jpg',
        iconUrl26: '../../assets/renginiai/Tarptautinė Šunų Paroda Druskininkuose 18/DSC_6555.jpg',
        iconUrl27: '../../assets/renginiai/Tarptautinė Šunų Paroda Druskininkuose 18/DSC_6556.jpg',
        iconUrl28: '../../assets/renginiai/Tarptautinė Šunų Paroda Druskininkuose 18/DSC_6558.jpg',
        iconUrl29: '../../assets/renginiai/Tarptautinė Šunų Paroda Druskininkuose 18/DSC_6559.jpg',
        iconUrl30: '../../assets/renginiai/Tarptautinė Šunų Paroda Druskininkuose 18/DSC_6560.jpg',
        iconUrl31: '../../assets/renginiai/Tarptautinė Šunų Paroda Druskininkuose 18/DSC_6562.jpg',
        iconUrl32: '../../assets/renginiai/Tarptautinė Šunų Paroda Druskininkuose 18/DSC_6567.jpg',
        iconUrl33: '../../assets/renginiai/Tarptautinė Šunų Paroda Druskininkuose 18/DSC_6569.jpg',
        iconUrl34: '../../assets/renginiai/Tarptautinė Šunų Paroda Druskininkuose 18/DSC_6570.jpg',
        iconUrl35: '../../assets/renginiai/Tarptautinė Šunų Paroda Druskininkuose 18/DSC_6576.jpg',
        iconUrl36: '../../assets/renginiai/Tarptautinė Šunų Paroda Druskininkuose 18/DSC_6578.jpg',
        iconUrl37: '../../assets/renginiai/Tarptautinė Šunų Paroda Druskininkuose 18/DSC_6580.jpg',
        iconUrl38: '../../assets/renginiai/Tarptautinė Šunų Paroda Druskininkuose 18/DSC_6581.jpg',
        iconUrl39: '../../assets/renginiai/Tarptautinė Šunų Paroda Druskininkuose 18/DSC_6584.jpg',
        iconUrl40: '../../assets/renginiai/Tarptautinė Šunų Paroda Druskininkuose 18/DSC_6592.jpg',
        iconUrl41: '',
        iconUrl1Alt: '',
        iconUrl2Alt: '',
        iconUrl3Alt: '',
        iconUrl4Alt: '',
        iconUrl5Alt: '',
        iconUrl6Alt: '',
        iconUrl7Alt: '',
        iconUrl8Alt: '',
        iconUrl9Alt: '',
        iconUrl10Alt: '',
        iconUrl11Alt: '',
        iconUrl12Alt: '',
        iconUrl13Alt: '',
        iconUrl14Alt: '',
        iconUrl15Alt: '',
        iconUrl16Alt: '',
        iconUrl17Alt: '',
        iconUrl18Alt: '',
        iconUrl19Alt: '',
        iconUrl20Alt: '',
        iconUrl21Alt: '',
        iconUrl22Alt: '',
        iconUrl23Alt: '',
        iconUrl24Alt: '',
        iconUrl25Alt: '',
        iconUrl26Alt: '',
        iconUrl27Alt: '',
        iconUrl28Alt: '',
        iconUrl29Alt: '',
        iconUrl30Alt: '',
        iconUrl31Alt: '',
        iconUrl32Alt: '',
        iconUrl33Alt: '',
        iconUrl34Alt: '',
        iconUrl35Alt: '',
        iconUrl36Alt: '',
        iconUrl37Alt: '',
        iconUrl38Alt: '',
        iconUrl39Alt: '',
        iconUrl40Alt: '',
        iconUrl41Alt: '',
        longDescription1: "",
        longDescription2: "",
        longDescription3: "",
        longDescription4: "",
        longDescription5: "",
        longDescription6: "",
        year: '2018',
        month: '01',
        day: '01',
        logoUrl1: "../../assets/LOGO/logo_vektorius.svg",
        logoUrl2: "",
        cardImg: ''
    },
    {
        id: 12,
        description: "Tarptautinė šunų paroda Vilniuje 19",
        videoUrl1: '',
        iconUrl1: '../../assets/renginiai/Tarptautinė šunų paroda VIlniuje 19/53381750_10214918300526025_3932553694955962368_o.jpg',
        iconUrl2: '../../assets/renginiai/Tarptautinė šunų paroda VIlniuje 19/53391186_10214918299245993_2909759047899021312_o.jpg',
        iconUrl3: '../../assets/renginiai/Tarptautinė šunų paroda VIlniuje 19/53392845_10214918298805982_171372253127114752_o.jpg',
        iconUrl4: '../../assets/renginiai/Tarptautinė šunų paroda VIlniuje 19/53578863_10214918300806032_7147654290188795904_o.jpg',
        iconUrl5: '../../assets/renginiai/Tarptautinė šunų paroda VIlniuje 19/53608549_10214929330121758_2872853433306578944_o.jpg',
        iconUrl6: '../../assets/renginiai/Tarptautinė šunų paroda VIlniuje 19/53652982_10214918301566051_597860654489010176_o.jpg',
        iconUrl7: '../../assets/renginiai/Tarptautinė šunų paroda VIlniuje 19/53677020_10214918300926035_111873126282821632_n.jpg',
        iconUrl8: '../../assets/renginiai/Tarptautinė šunų paroda VIlniuje 19/53688831_10214929328521718_7023431457892728832_o.jpg',
        iconUrl9: '../../assets/renginiai/Tarptautinė šunų paroda VIlniuje 19/53694004_10214929331081782_435366841792069632_o.jpg',
        iconUrl10: '../../assets/renginiai/Tarptautinė šunų paroda VIlniuje 19/53792513_10214918300646028_2664427913201319936_o.jpg',
        iconUrl11: '../../assets/renginiai/Tarptautinė šunų paroda VIlniuje 19/54409197_10214929327321688_3897057314967912448_n.jpg',
        iconUrl12: '../../assets/renginiai/Tarptautinė šunų paroda VIlniuje 19/53860976_10214918299526000_1649797135685648384_o.jpg',
        iconUrl13: '../../assets/renginiai/Tarptautinė šunų paroda VIlniuje 19/53860976_10214918299526000_1649797135685648384_o_(1).jpg',
        iconUrl14: '../../assets/renginiai/Tarptautinė šunų paroda VIlniuje 19/53906713_10214918299566001_7435003845857509376_n.jpg',
        iconUrl15: '../../assets/renginiai/Tarptautinė šunų paroda VIlniuje 19/54041354_10214929330681772_3879696460157026304_o.jpg',
        iconUrl16: '../../assets/renginiai/Tarptautinė šunų paroda VIlniuje 19/54190762_10214929329481742_8761143593420193792_o.jpg',
        iconUrl17: '../../assets/renginiai/Tarptautinė šunų paroda VIlniuje 19/54207542_10214918300086014_5086979756671369216_n.jpg',
        iconUrl18: '',
        iconUrl19: '',
        iconUrl20: '',
        iconUrl21: '',
        iconUrl22: '',
        iconUrl23: '',
        iconUrl24: '',
        iconUrl25: '',
        iconUrl26: '',
        iconUrl27: '',
        iconUrl28: '',
        iconUrl29: '',
        iconUrl30: '',
        iconUrl31: '',
        iconUrl32: '',
        iconUrl33: '',
        iconUrl34: '',
        iconUrl35: '',
        iconUrl36: '',
        iconUrl37: '',
        iconUrl38: '',
        iconUrl39: '',
        iconUrl40: '',
        iconUrl41: '',
        iconUrl1Alt: '',
        iconUrl2Alt: '',
        iconUrl3Alt: '',
        iconUrl4Alt: '',
        iconUrl5Alt: '',
        iconUrl6Alt: '',
        iconUrl7Alt: '',
        iconUrl8Alt: '',
        iconUrl9Alt: '',
        iconUrl10Alt: '',
        iconUrl11Alt: '',
        iconUrl12Alt: '',
        iconUrl13Alt: '',
        iconUrl14Alt: '',
        iconUrl15Alt: '',
        iconUrl16Alt: '',
        iconUrl17Alt: '',
        iconUrl18Alt: '',
        iconUrl19Alt: '',
        iconUrl20Alt: '',
        iconUrl21Alt: '',
        iconUrl22Alt: '',
        iconUrl23Alt: '',
        iconUrl24Alt: '',
        iconUrl25Alt: '',
        iconUrl26Alt: '',
        iconUrl27Alt: '',
        iconUrl28Alt: '',
        iconUrl29Alt: '',
        iconUrl30Alt: '',
        iconUrl31Alt: '',
        iconUrl32Alt: '',
        iconUrl33Alt: '',
        iconUrl34Alt: '',
        iconUrl35Alt: '',
        iconUrl36Alt: '',
        iconUrl37Alt: '',
        iconUrl38Alt: '',
        iconUrl39Alt: '',
        iconUrl40Alt: '',
        iconUrl41Alt: '',
        longDescription1: "",
        longDescription2: "",
        longDescription3: "",
        longDescription4: "",
        longDescription5: "",
        longDescription6: "",
        year: '2019',
        month: '01',
        day: '01',
        logoUrl1: "../../assets/LOGO/logo_vektorius.svg",
        logoUrl2: "",
        cardImg: ''
    },
    {
        id: 13,
        description: "Tarptautinės žirgų konkūrų varžybos 15",
        videoUrl1: '',
        iconUrl1: '../../assets/renginiai/Tarptautinės žirgų konkurų varžybos 15/DSC_0002.JPG',
        iconUrl2: '../../assets/renginiai/Tarptautinės žirgų konkurų varžybos 15/DSC_0007.JPG',
        iconUrl3: '../../assets/renginiai/Tarptautinės žirgų konkurų varžybos 15/DSC_0015.JPG',
        iconUrl4: '../../assets/renginiai/Tarptautinės žirgų konkurų varžybos 15/DSC_0029.JPG',
        iconUrl5: '../../assets/renginiai/Tarptautinės žirgų konkurų varžybos 15/DSC_0033.JPG',
        iconUrl6: '../../assets/renginiai/Tarptautinės žirgų konkurų varžybos 15/DSC_0036.JPG',
        iconUrl7: '../../assets/renginiai/Tarptautinės žirgų konkurų varžybos 15/DSC_0040.JPG',
        iconUrl8: '../../assets/renginiai/Tarptautinės žirgų konkurų varžybos 15/DSC_0052.JPG',
        iconUrl9: '../../assets/renginiai/Tarptautinės žirgų konkurų varžybos 15/DSC_0055.JPG',
        iconUrl10: '../../assets/renginiai/Tarptautinės žirgų konkurų varžybos 15/DSC_0056.JPG',
        iconUrl11: '../../assets/renginiai/Tarptautinės žirgų konkurų varžybos 15/DSC_0165.JPG',
        iconUrl12: '../../assets/renginiai/Tarptautinės žirgų konkurų varžybos 15/DSC_0069.JPG',
        iconUrl13: '../../assets/renginiai/Tarptautinės žirgų konkurų varžybos 15/DSC_0075.JPG',
        iconUrl14: '../../assets/renginiai/Tarptautinės žirgų konkurų varžybos 15/DSC_0086.JPG',
        iconUrl15: '../../assets/renginiai/Tarptautinės žirgų konkurų varžybos 15/DSC_0095.JPG',
        iconUrl16: '../../assets/renginiai/Tarptautinės žirgų konkurų varžybos 15/DSC_0106.JPG',
        iconUrl17: '../../assets/renginiai/Tarptautinės žirgų konkurų varžybos 15/DSC_0111.JPG',
        iconUrl18: '../../assets/renginiai/Tarptautinės žirgų konkurų varžybos 15/DSC_0115.JPG',
        iconUrl19: '../../assets/renginiai/Tarptautinės žirgų konkurų varžybos 15/DSC_0116.JPG',
        iconUrl20: '../../assets/renginiai/Tarptautinės žirgų konkurų varžybos 15/DSC_0118.JPG',
        iconUrl21: '../../assets/renginiai/Tarptautinės žirgų konkurų varžybos 15/DSC_0121.JPG',
        iconUrl22: '../../assets/renginiai/Tarptautinės žirgų konkurų varžybos 15/DSC_0123.JPG',
        iconUrl23: '../../assets/renginiai/Tarptautinės žirgų konkurų varžybos 15/DSC_0125.JPG',
        iconUrl24: '../../assets/renginiai/Tarptautinės žirgų konkurų varžybos 15/DSC_0127.JPG',
        iconUrl25: '../../assets/renginiai/Tarptautinės žirgų konkurų varžybos 15/DSC_0131.JPG',
        iconUrl26: '../../assets/renginiai/Tarptautinės žirgų konkurų varžybos 15/DSC_0134.JPG',
        iconUrl27: '../../assets/renginiai/Tarptautinės žirgų konkurų varžybos 15/DSC_0139.JPG',
        iconUrl28: '../../assets/renginiai/Tarptautinės žirgų konkurų varžybos 15/DSC_0141.JPG',
        iconUrl29: '../../assets/renginiai/Tarptautinės žirgų konkurų varžybos 15/DSC_0147.JPG',
        iconUrl30: '../../assets/renginiai/Tarptautinės žirgų konkurų varžybos 15/DSC_0149.JPG',
        iconUrl31: '../../assets/renginiai/Tarptautinės žirgų konkurų varžybos 15/DSC_0150.JPG',
        iconUrl32: '../../assets/renginiai/Tarptautinės žirgų konkurų varžybos 15/DSC_0156.JPG',
        iconUrl33: '../../assets/renginiai/Tarptautinės žirgų konkurų varžybos 15/DSC_0160.JPG',
        iconUrl34: '',
        iconUrl35: '',
        iconUrl36: '',
        iconUrl37: '',
        iconUrl38: '',
        iconUrl39: '',
        iconUrl40: '',
        iconUrl41: '',
        iconUrl1Alt: '',
        iconUrl2Alt: '',
        iconUrl3Alt: '',
        iconUrl4Alt: '',
        iconUrl5Alt: '',
        iconUrl6Alt: '',
        iconUrl7Alt: '',
        iconUrl8Alt: '',
        iconUrl9Alt: '',
        iconUrl10Alt: '',
        iconUrl11Alt: '',
        iconUrl12Alt: '',
        iconUrl13Alt: '',
        iconUrl14Alt: '',
        iconUrl15Alt: '',
        iconUrl16Alt: '',
        iconUrl17Alt: '',
        iconUrl18Alt: '',
        iconUrl19Alt: '',
        iconUrl20Alt: '',
        iconUrl21Alt: '',
        iconUrl22Alt: '',
        iconUrl23Alt: '',
        iconUrl24Alt: '',
        iconUrl25Alt: '',
        iconUrl26Alt: '',
        iconUrl27Alt: '',
        iconUrl28Alt: '',
        iconUrl29Alt: '',
        iconUrl30Alt: '',
        iconUrl31Alt: '',
        iconUrl32Alt: '',
        iconUrl33Alt: '',
        iconUrl34Alt: '',
        iconUrl35Alt: '',
        iconUrl36Alt: '',
        iconUrl37Alt: '',
        iconUrl38Alt: '',
        iconUrl39Alt: '',
        iconUrl40Alt: '',
        iconUrl41Alt: '',
        longDescription1: "",
        longDescription2: "",
        longDescription3: "",
        longDescription4: "",
        longDescription5: "",
        longDescription6: "",
        year: '2015',
        month: '01',
        day: '01',
        logoUrl1: "../../assets/LOGO/logo_vektorius.svg",
        logoUrl2: "",
        cardImg: ''
    },
    {
        id: 14,
        description: "Laimingos Uodegos 16",
        videoUrl1: '',
        iconUrl1: '../../assets/renginiai/Laimingos Uodegos 16/IMG_1195.JPG',
        iconUrl2: '../../assets/renginiai/Laimingos Uodegos 16/IMG_1213.JPG',
        iconUrl3: '../../assets/renginiai/Laimingos Uodegos 16/IMG_1236.JPG',
        iconUrl4: '../../assets/renginiai/Laimingos Uodegos 16/IMG_1269.JPG',
        iconUrl5: '../../assets/renginiai/Laimingos Uodegos 16/IMG_1271.JPG',
        iconUrl6: '../../assets/renginiai/Laimingos Uodegos 16/IMG_1275.JPG',
        iconUrl7: '../../assets/renginiai/Laimingos Uodegos 16/IMG_1276.JPG',
        iconUrl8: '../../assets/renginiai/Laimingos Uodegos 16/IMG_1308.JPG',
        iconUrl9: '../../assets/renginiai/Laimingos Uodegos 16/IMG_1506.JPG',
        iconUrl10: '../../assets/renginiai/Laimingos Uodegos 16/IMG_1517.JPG',
        iconUrl11: '../../assets/renginiai/Laimingos Uodegos 16/IMG_1524.JPG',
        iconUrl12: '',
        iconUrl13: '',
        iconUrl14: '',
        iconUrl15: '',
        iconUrl16: '',
        iconUrl17: '',
        iconUrl18: '',
        iconUrl19: '',
        iconUrl20: '',
        iconUrl21: '',
        iconUrl22: '',
        iconUrl23: '',
        iconUrl24: '',
        iconUrl25: '',
        iconUrl26: '',
        iconUrl27: '',
        iconUrl28: '',
        iconUrl29: '',
        iconUrl30: '',
        iconUrl31: '',
        iconUrl32: '',
        iconUrl33: '',
        iconUrl34: '',
        iconUrl35: '',
        iconUrl36: '',
        iconUrl37: '',
        iconUrl38: '',
        iconUrl39: '',
        iconUrl40: '',
        iconUrl41: '',
        iconUrl1Alt: '',
        iconUrl2Alt: '',
        iconUrl3Alt: '',
        iconUrl4Alt: '',
        iconUrl5Alt: '',
        iconUrl6Alt: '',
        iconUrl7Alt: '',
        iconUrl8Alt: '',
        iconUrl9Alt: '',
        iconUrl10Alt: '',
        iconUrl11Alt: '',
        iconUrl12Alt: '',
        iconUrl13Alt: '',
        iconUrl14Alt: '',
        iconUrl15Alt: '',
        iconUrl16Alt: '',
        iconUrl17Alt: '',
        iconUrl18Alt: '',
        iconUrl19Alt: '',
        iconUrl20Alt: '',
        iconUrl21Alt: '',
        iconUrl22Alt: '',
        iconUrl23Alt: '',
        iconUrl24Alt: '',
        iconUrl25Alt: '',
        iconUrl26Alt: '',
        iconUrl27Alt: '',
        iconUrl28Alt: '',
        iconUrl29Alt: '',
        iconUrl30Alt: '',
        iconUrl31Alt: '',
        iconUrl32Alt: '',
        iconUrl33Alt: '',
        iconUrl34Alt: '',
        iconUrl35Alt: '',
        iconUrl36Alt: '',
        iconUrl37Alt: '',
        iconUrl38Alt: '',
        iconUrl39Alt: '',
        iconUrl40Alt: '',
        iconUrl41Alt: '',
        longDescription1: "",
        longDescription2: "",
        longDescription3: "",
        longDescription4: "",
        longDescription5: "",
        longDescription6: "",
        year: '2016',
        month: '01',
        day: '01',
        logoUrl1: "../../assets/LOGO/logo_vektorius.svg",
        logoUrl2: "",
        cardImg: ''
    },
    {
        id: 15,
        description: "Gyvūnų mylėtojų šventė Vilniuje 17",
        videoUrl1: '',
        iconUrl1: '../../assets/renginiai/Gyvūnų mylėtojų šventė Vilniuje 17/1.jpg',
        iconUrl2: '../../assets/renginiai/Gyvūnų mylėtojų šventė Vilniuje 17/2.jpg',
        iconUrl3: '../../assets/renginiai/Gyvūnų mylėtojų šventė Vilniuje 17/3.jpg',
        iconUrl4: '../../assets/renginiai/Gyvūnų mylėtojų šventė Vilniuje 17/4.jpg',
        iconUrl5: '../../assets/renginiai/Gyvūnų mylėtojų šventė Vilniuje 17/5.jpg',
        iconUrl6: '../../assets/renginiai/Gyvūnų mylėtojų šventė Vilniuje 17/6.jpg',
        iconUrl7: '../../assets/renginiai/Gyvūnų mylėtojų šventė Vilniuje 17/7.jpg',
        iconUrl8: '../../assets/renginiai/Gyvūnų mylėtojų šventė Vilniuje 17/8.jpg',
        iconUrl9: '../../assets/renginiai/Gyvūnų mylėtojų šventė Vilniuje 17/9.jpg',
        iconUrl10: '../../assets/renginiai/Gyvūnų mylėtojų šventė Vilniuje 17/10.jpg',
        iconUrl11: '../../assets/renginiai/Gyvūnų mylėtojų šventė Vilniuje 17/11.jpg',
        iconUrl12: '../../assets/renginiai/Gyvūnų mylėtojų šventė Vilniuje 17/12.jpg',
        iconUrl13: '../../assets/renginiai/Gyvūnų mylėtojų šventė Vilniuje 17/13.jpg',
        iconUrl14: '../../assets/renginiai/Gyvūnų mylėtojų šventė Vilniuje 17/14.jpg',
        iconUrl15: '../../assets/renginiai/Gyvūnų mylėtojų šventė Vilniuje 17/15.jpg',
        iconUrl16: '../../assets/renginiai/Gyvūnų mylėtojų šventė Vilniuje 17/16.jpg',
        iconUrl17: '../../assets/renginiai/Gyvūnų mylėtojų šventė Vilniuje 17/17.jpg',
        iconUrl18: '../../assets/renginiai/Gyvūnų mylėtojų šventė Vilniuje 17/18.jpg',
        iconUrl19: '../../assets/renginiai/Gyvūnų mylėtojų šventė Vilniuje 17/19.jpg',
        iconUrl20: '../../assets/renginiai/Gyvūnų mylėtojų šventė Vilniuje 17/20.jpg',
        iconUrl21: '../../assets/renginiai/Gyvūnų mylėtojų šventė Vilniuje 17/21.jpg',
        iconUrl22: '../../assets/renginiai/Gyvūnų mylėtojų šventė Vilniuje 17/22.jpg',
        iconUrl23: '../../assets/renginiai/Gyvūnų mylėtojų šventė Vilniuje 17/23.jpg',
        iconUrl24: '',
        iconUrl25: '',
        iconUrl26: '',
        iconUrl27: '',
        iconUrl28: '',
        iconUrl29: '',
        iconUrl30: '',
        iconUrl31: '',
        iconUrl32: '',
        iconUrl33: '',
        iconUrl34: '',
        iconUrl35: '',
        iconUrl36: '',
        iconUrl37: '',
        iconUrl38: '',
        iconUrl39: '',
        iconUrl40: '',
        iconUrl41: '',
        iconUrl1Alt: '',
        iconUrl2Alt: '',
        iconUrl3Alt: '',
        iconUrl4Alt: '',
        iconUrl5Alt: '',
        iconUrl6Alt: '',
        iconUrl7Alt: '',
        iconUrl8Alt: '',
        iconUrl9Alt: '',
        iconUrl10Alt: '',
        iconUrl11Alt: '',
        iconUrl12Alt: '',
        iconUrl13Alt: '',
        iconUrl14Alt: '',
        iconUrl15Alt: '',
        iconUrl16Alt: '',
        iconUrl17Alt: '',
        iconUrl18Alt: '',
        iconUrl19Alt: '',
        iconUrl20Alt: '',
        iconUrl21Alt: '',
        iconUrl22Alt: '',
        iconUrl23Alt: '',
        iconUrl24Alt: '',
        iconUrl25Alt: '',
        iconUrl26Alt: '',
        iconUrl27Alt: '',
        iconUrl28Alt: '',
        iconUrl29Alt: '',
        iconUrl30Alt: '',
        iconUrl31Alt: '',
        iconUrl32Alt: '',
        iconUrl33Alt: '',
        iconUrl34Alt: '',
        iconUrl35Alt: '',
        iconUrl36Alt: '',
        iconUrl37Alt: '',
        iconUrl38Alt: '',
        iconUrl39Alt: '',
        iconUrl40Alt: '',
        iconUrl41Alt: '',
        longDescription1: "",
        longDescription2: "",
        longDescription3: "",
        longDescription4: "",
        longDescription5: "",
        longDescription6: "",
        year: '2017',
        month: '01',
        day: '01',
        logoUrl1: "../../assets/LOGO/logo_vektorius.svg",
        logoUrl2: "",
        cardImg: ''
    },

    {
        id: 16,
        description: "TESTINIS",
        videoUrl1: '',
        iconUrl1: '../../assets/renginiai/Gyvūnų mylėtojų šventė Vilniuje 17/1.jpg',
        iconUrl2: '../../assets/renginiai/Gyvūnų mylėtojų šventė Vilniuje 17/2.jpg',
        iconUrl3: '../../assets/renginiai/Gyvūnų mylėtojų šventė Vilniuje 17/3.jpg',
        iconUrl4: '../../assets/renginiai/Gyvūnų mylėtojų šventė Vilniuje 17/4.jpg',
        iconUrl5: '../../assets/renginiai/Gyvūnų mylėtojų šventė Vilniuje 17/5.jpg',
        iconUrl6: '../../assets/renginiai/Gyvūnų mylėtojų šventė Vilniuje 17/6.jpg',
        iconUrl7: '../../assets/renginiai/Gyvūnų mylėtojų šventė Vilniuje 17/7.jpg',
        iconUrl8: '../../assets/renginiai/Gyvūnų mylėtojų šventė Vilniuje 17/8.jpg',
        iconUrl9: '../../assets/renginiai/Gyvūnų mylėtojų šventė Vilniuje 17/9.jpg',
        iconUrl10: '../../assets/renginiai/Gyvūnų mylėtojų šventė Vilniuje 17/10.jpg',
        iconUrl11: '../../assets/renginiai/Gyvūnų mylėtojų šventė Vilniuje 17/11.jpg',
        iconUrl12: '../../assets/renginiai/Gyvūnų mylėtojų šventė Vilniuje 17/12.jpg',
        iconUrl13: '../../assets/renginiai/Gyvūnų mylėtojų šventė Vilniuje 17/13.jpg',
        iconUrl14: '../../assets/renginiai/Gyvūnų mylėtojų šventė Vilniuje 17/14.jpg',
        iconUrl15: '../../assets/renginiai/Gyvūnų mylėtojų šventė Vilniuje 17/15.jpg',
        iconUrl16: '../../assets/renginiai/Gyvūnų mylėtojų šventė Vilniuje 17/16.jpg',
        iconUrl17: '../../assets/renginiai/Gyvūnų mylėtojų šventė Vilniuje 17/17.jpg',
        iconUrl18: '../../assets/renginiai/Gyvūnų mylėtojų šventė Vilniuje 17/18.jpg',
        iconUrl19: '../../assets/renginiai/Gyvūnų mylėtojų šventė Vilniuje 17/19.jpg',
        iconUrl20: '../../assets/renginiai/Gyvūnų mylėtojų šventė Vilniuje 17/20.jpg',
        iconUrl21: '../../assets/renginiai/Gyvūnų mylėtojų šventė Vilniuje 17/21.jpg',
        iconUrl22: '../../assets/renginiai/Gyvūnų mylėtojų šventė Vilniuje 17/22.jpg',
        iconUrl23: '../../assets/renginiai/Gyvūnų mylėtojų šventė Vilniuje 17/23.jpg',
        iconUrl24: '',
        iconUrl25: '',
        iconUrl26: '',
        iconUrl27: '',
        iconUrl28: '',
        iconUrl29: '',
        iconUrl30: '',
        iconUrl31: '',
        iconUrl32: '',
        iconUrl33: '',
        iconUrl34: '',
        iconUrl35: '',
        iconUrl36: '',
        iconUrl37: '',
        iconUrl38: '',
        iconUrl39: '',
        iconUrl40: '',
        iconUrl41: '',
        iconUrl1Alt: '',
        iconUrl2Alt: '',
        iconUrl3Alt: '',
        iconUrl4Alt: '',
        iconUrl5Alt: '',
        iconUrl6Alt: '',
        iconUrl7Alt: '',
        iconUrl8Alt: '',
        iconUrl9Alt: '',
        iconUrl10Alt: '',
        iconUrl11Alt: '',
        iconUrl12Alt: '',
        iconUrl13Alt: '',
        iconUrl14Alt: '',
        iconUrl15Alt: '',
        iconUrl16Alt: '',
        iconUrl17Alt: '',
        iconUrl18Alt: '',
        iconUrl19Alt: '',
        iconUrl20Alt: '',
        iconUrl21Alt: '',
        iconUrl22Alt: '',
        iconUrl23Alt: '',
        iconUrl24Alt: '',
        iconUrl25Alt: '',
        iconUrl26Alt: '',
        iconUrl27Alt: '',
        iconUrl28Alt: '',
        iconUrl29Alt: '',
        iconUrl30Alt: '',
        iconUrl31Alt: '',
        iconUrl32Alt: '',
        iconUrl33Alt: '',
        iconUrl34Alt: '',
        iconUrl35Alt: '',
        iconUrl36Alt: '',
        iconUrl37Alt: '',
        iconUrl38Alt: '',
        iconUrl39Alt: '',
        iconUrl40Alt: '',
        iconUrl41Alt: '',
        longDescription1: "",
        longDescription2: "",
        longDescription3: "",
        longDescription4: "",
        longDescription5: "",
        longDescription6: "",
        year: '2017',
        month: '01',
        day: '01',
        logoUrl1: "../../assets/LOGO/logo_vektorius.svg",
        logoUrl2: "",
        cardImg: '../../assets/renginiai/Gyvūnų mylėtojų šventė Vilniuje 17/23.jpg'
    }
]
