export const SUNUVEISLYNAS: any = [

    {
        title11: 'BELGŲ AVIGANIŲ MALINUA VEISLYNAS',
        iconUrl1: '../../assets/sunu-veislynas/Amiga Aktyvi Linija.jpg',
        iconUrl1Alt: 'Amiga Aktyvi Linija',
        iconUrl2: '../assets/sunu-veislynas/Elena Balzbig.jpg',
        iconUrl2Alt: 'Elena Balzbig',
        iconUrl3: '../assets/sunu-veislynas/Rakštis Laukinė Orchidėja.jpg',
        iconUrl3Alt: 'Rakštis Laukinė Orchidėja',
        iconUrl4: '../assets/sunu-veislynas/Iron Degantis Kraujas.jpg',
        iconUrl4Alt: 'Iron Degantis Kraujas -LTCH -JLTCH ',
        iconUrl5: '',
        iconUrl5Alt: '',
        iconUrl6: '', 
        iconUrl6Alt: '',
        

        title21: '',
        description21: '',
        description22: '',
        description23: '',

        title31: '',
        description31: '',
        description32: '',
        description33: '',

        
        description41: '',
        description42: '',
        description43: '',
        iconUrl41: '',
        iconUrl42: '',
        iconUrl43: '',
        iconUrl44: '',
        iconUrl45: '',
        iconUrl46: '',
        iconUrl47: '',
        iconUrl48: '',
        iconUrl49: '',
        iconUrl410: '',
        iconUrl411: '',
        iconUrl412: '', 
        iconUrl413: '',
        iconUrl414: '',
        iconUrl415: '',
        iconUrl416: '',

        title51: '',
        description51: '',
        description52: '',
        description53: '',

        image6: '',
        imageAlt6: '',
        description61: '',
        description62: '',
        description63: '',
        iconUrl61: '',
        iconUrl62: '',
        iconUrl63: '',
        iconUrl64: '',
        iconUrl65: '',
        iconUrl66: '',
        iconUrl67: '',
        iconUrl68: '',
        iconUrl69: '',
        iconUrl610: '',
        iconUrl611: '',
        iconUrl612: '', 
        iconUrl613: '',
        iconUrl614: '',
        iconUrl615: '',
        iconUrl616: '',

        title71: '',
        description71: '',
        description72: '',
        description73: '',

        image8: '',
        imageAlt8: '',
        description81: '',
        description82: '',
        description83: '',
        iconUrl81: '',
        iconUrl82: '',
        iconUrl83: '',
        iconUrl84: '',
        iconUrl85: '',
        iconUrl86: '',
        iconUrl87: '',
        iconUrl88: '',
        iconUrl89: '',
        iconUrl810: '',
        iconUrl811: '',
        iconUrl812: '', 
        iconUrl813: '',
        iconUrl814: '',
        iconUrl815: '',
        iconUrl816: '',

        title91: '',
        description91: '',
        description92: '',
        description93: '',

        image10: '',
        imageAlt10: '',
        description101: '',
        description102: '',
        description103: '',
        iconUrl101: '',
        iconUrl102: '',
        iconUrl103: '',
        iconUrl104: '',
        iconUrl105: '',
        iconUrl106: '',
        iconUrl107: '',
        iconUrl108: '',
        iconUrl109: '',
        iconUrl1010: '',
        iconUrl1011: '',
        iconUrl1012: '', 
        iconUrl1013: '',
        iconUrl1014: '',
        iconUrl1015: '',
        iconUrl1016: '',

        title111: '',
        description111: '',
        description112: '',
        description113: '',

        image12: '',
        imageAlt12: '',
        description121: '',
        description122: '',
        description123: '',
        iconUrl121: '',
        iconUrl122: '',
        iconUrl123: '',
        iconUrl124: '',
        iconUrl125: '',
        iconUrl126: '',
        iconUrl127: '',
        iconUrl128: '',
        iconUrl129: '',
        iconUrl1210: '',
        iconUrl1211: '',
        iconUrl1212: '', 
        iconUrl1213: '',
        iconUrl1214: '',
        iconUrl1215: '',
        iconUrl1216: '',

        title131: '',
        description131: '',
        description132: '',
        description133: '',
    }
]